[CU-1zhbq08] Develop STE Hero Section
waterloop/waterloop-website-w20 pull request #127
Opened 2022-03-02 00:27 UTC by Samanthatb1

## Changes
> Added Hero SVG and Logo SVG
> Created Sign Up button

## Type of change
- [x] New feature 

## Note
- Issues with the logo SVG whitespace causes the page to overflow, encouraging other members to take a look

# How Has This Been Tested?
- [x] Checked responsiveness in developer tools, issues remain as previously mentioned

<img width="580" alt="Screen Shot 2022-03-01 at 7 26 44 PM" src="https://user-images.githubusercontent.com/62915953/156271491-652efde0-fc18-4fd4-a652-2deb3e2a4f2e.png">

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation/READ-ME/UMLS
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-03-02 00:27 UTC, jennchenn commented
Task linked: [CU-1zhbq08 Develop STE hero section](https://app.clickup.com/t/1zhbq08)

2022-03-02 04:20 UTC, williamhpark requested changes
I'm still trying to figure out the logo issue, but these are some other suggestions I have in the meantime. Edit: Was able to fix the SVG issue, refer to the comments.

2022-03-02 04:20 UTC, williamhpark commented on waterloop-site/src/components/SustainableTech/Hero/Hero.tsx
> +  padding: 60px 0 30px;
Is this required? When I run the branch I see an empty blue space at the bottom, and removing this padding fixes that.

2022-03-02 04:20 UTC, williamhpark commented on waterloop-site/src/components/SustainableTech/Hero/Hero.tsx
> +bigger but doesnt solve the problem */
This should be deleted before merging.

2022-03-02 04:20 UTC, williamhpark commented on waterloop-site/src/components/SustainableTech/Hero/Hero.tsx
> +  height: 100vh;
More than height, I think `width` is more important. Currently, the SVG doesn't fill up the entire width of the screen. I would replace this with `width: 100%`

2022-03-02 04:20 UTC, williamhpark commented on waterloop-site/src/components/SustainableTech/Hero/Hero.tsx
> +  background-color: #e5f6fa;
Don't believe you need this?

2022-03-02 04:20 UTC, williamhpark commented on waterloop-site/src/components/SustainableTech/Hero/Hero.tsx
> +          Sign Up
This should be capitalized, to match the Figma design.

2022-03-06 02:01 UTC, williamhpark approved these changes
Just one small change suggestion, then looks good to me!

2022-03-06 02:01 UTC, williamhpark commented on waterloop-site/src/components/SustainableTech/Hero/Hero.tsx
> +      <ButtonContainer as="a" href="https://tinyurl.com/uwgreentech">
Can you make clicking this open a new tab by adding `target="_blank" rel="noopener noreferrer"`?

2022-03-06 18:47 UTC, eevanwong reviewed
![image](https://user-images.githubusercontent.com/71536798/156936868-aaa682f4-4861-425a-84f1-fe98f7031c55.png)

On my screen its a bit cut off :/. I have a relatively large monitor so I think in order to match the size of my monitor. The `100vh` height was not enough to maintain the aspect ratio of the original image. 

I've attempted other options to control the height, but it would be ideal that height was only `100vh`. 

In the `LandingContainer` div, I've tried to experiment with how it covers it (e.g `background-size: contain;` which leads to: 
![image](https://user-images.githubusercontent.com/71536798/156937530-a7950ffd-5d66-4437-8aec-6249f2cd5324.png).

Other than that, everything else looks good! As a potential workaround, we could change the actual figma such that the goose is a bit farther up (but make it smaller) so that it's not evidently cropped.

2022-03-06 18:52 UTC, eevanwong requested changes
To avoid the cropping issue, a potential solution may be to adjust the figma component by moving the large goose at the front a little bit up and make it smaller so that there is more of the blue at the bottom.

This would allow us to be more forgiving in terms of cropping in different screens.

2022-03-08 06:49 UTC, williamhpark approved these changes

2022-03-08 06:49 UTC, merged