Make hero mobile responsive
waterloop/waterloop-website-w20 pull request #140
Opened 2022-03-18 05:28 UTC by lisazhao30

**Changes**

- Changed mobile background image
- Removed the divider because it doesn't really line up with the mobile image

**How Has This Been Tested?**

- [x] Verified that the design matches the figma
- [x] Tested responsiveness in mobile mode

**Images**
<img width="431" alt="Screen Shot 2022-03-18 at 12 53 14 AM" src="https://user-images.githubusercontent.com/84100023/158942864-d1158c7d-f545-4176-9bd8-b07676709977.png">
<img width="384" alt="Screen Shot 2022-03-18 at 1 26 58 AM" src="https://user-images.githubusercontent.com/84100023/158942856-284f15f6-ad77-4af7-aecd-fafb40f22f92.png">
e

2022-03-18 05:28 UTC, jennchenn commented
Task linked: [CU-233uwk0 Make hero mobile responsive](https://app.clickup.com/t/233uwk0)

2022-03-20 00:47 UTC, williamhpark requested changes
Looks great! Just one thing though, I checked it out in one particular viewport and there's a small gap between the landing image and the top bar. Could you remove this gap? All other viewports looked fine to me.

<img width="572" alt="image" src="https://user-images.githubusercontent.com/53918631/159143349-6fdf30ff-7343-4ee0-a72b-40d4ea33b508.png">

2022-03-20 02:17 UTC, lisazhao30 commented
just fixed it :)

2022-05-04 14:55 UTC, jmawloo approved these changes

2022-05-04 14:56 UTC, merged